Traceback (most recent call last):
  File "./Projects/CDP/main.py", line 59, in <module>
    main(args)
  File "./Projects/CDP/main.py", line 42, in main
    workspace.evaluate()
  File "/home/s222126776/Projects/CDP/workspaces/cdp.py", line 547, in evaluate
    self.agent.load(self.logger_cfg['log_dir']+'model',-1)
  File "/home/s222126776/Projects/CDP/agent/sac.py", line 163, in load
    torch.load('%s/actor_%s.pt' % (model_dir, step))
  File "/home/s222126776/Projects/CDP2/env/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/s222126776/Projects/CDP2/env/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/s222126776/Projects/CDP2/env/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/s222126776/Projects/CDP/experiments/Mujoco/HC/beta3/90678/0.9/run_back/model/actor_-1.pt'
Traceback (most recent call last):
  File "./Projects/CDP/main.py", line 59, in <module>
    main(args)
  File "./Projects/CDP/main.py", line 42, in main
    workspace.evaluate()
  File "/home/s222126776/Projects/CDP/workspaces/cdp.py", line 547, in evaluate
    self.agent.load(self.logger_cfg['log_dir']+'model',-1)
  File "/home/s222126776/Projects/CDP/agent/sac.py", line 163, in load
    torch.load('%s/actor_%s.pt' % (model_dir, step))
  File "/home/s222126776/Projects/CDP2/env/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/s222126776/Projects/CDP2/env/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/s222126776/Projects/CDP2/env/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/s222126776/Projects/CDP/experiments/Mujoco/HC/beta3/89067/0.9/run_back/model/actor_-1.pt'
srun: error: a100-4: task 0: Exited with exit code 1
srun: error: a100-4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "./Projects/CDP/main.py", line 59, in <module>
    main(args)
  File "./Projects/CDP/main.py", line 42, in main
    workspace.evaluate()
  File "/home/s222126776/Projects/CDP/workspaces/cdp.py", line 547, in evaluate
    self.agent.load(self.logger_cfg['log_dir']+'model',-1)
  File "/home/s222126776/Projects/CDP/agent/sac.py", line 163, in load
    torch.load('%s/actor_%s.pt' % (model_dir, step))
  File "/home/s222126776/Projects/CDP2/env/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/s222126776/Projects/CDP2/env/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/s222126776/Projects/CDP2/env/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/s222126776/Projects/CDP/experiments/Mujoco/HC/beta3/78906/0.9/run_back/model/actor_-1.pt'
srun: error: a100-4: task 0: Exited with exit code 1
