usage: main.py [-h] [-method METHOD] [-config CONFIG] [-dir DIR]
               [-file_name FILE_NAME] [-seed SEED] [-task TASK] [-beta BETA]
main.py: error: argument -seed: invalid int value: '78906,'
usage: main.py [-h] [-method METHOD] [-config CONFIG] [-dir DIR]
               [-file_name FILE_NAME] [-seed SEED] [-task TASK] [-beta BETA]
main.py: error: argument -seed: invalid int value: '89067,'
srun: error: 4gpu-02: task 0: Exited with exit code 2
usage: main.py [-h] [-method METHOD] [-config CONFIG] [-dir DIR]
               [-file_name FILE_NAME] [-seed SEED] [-task TASK] [-beta BETA]
main.py: error: argument -seed: invalid int value: '90678,'
srun: error: 4gpu-02: task 0: Exited with exit code 2
srun: error: 4gpu-02: task 0: Exited with exit code 2
Traceback (most recent call last):
  File "./Projects/CDP/main.py", line 49, in <module>
    main(args)
  File "./Projects/CDP/main.py", line 30, in main
    workspace = cdp(cfg)
  File "/home/s222126776/Projects/CDP/workspaces/cdp.py", line 37, in __init__
    self.sac_smm_cfg = self.cfg['SAC_SMM']
KeyError: 'SAC_SMM'
Traceback (most recent call last):
  File "./Projects/CDP/main.py", line 49, in <module>
    main(args)
  File "./Projects/CDP/main.py", line 30, in main
    workspace = cdp(cfg)
  File "/home/s222126776/Projects/CDP/workspaces/cdp.py", line 37, in __init__
    self.sac_smm_cfg = self.cfg['SAC_SMM']
KeyError: 'SAC_SMM'
Traceback (most recent call last):
  File "./Projects/CDP/main.py", line 49, in <module>
    main(args)
  File "./Projects/CDP/main.py", line 30, in main
    workspace = cdp(cfg)
  File "/home/s222126776/Projects/CDP/workspaces/cdp.py", line 37, in __init__
    self.sac_smm_cfg = self.cfg['SAC_SMM']
KeyError: 'SAC_SMM'
Traceback (most recent call last):
  File "./Projects/CDP/main.py", line 49, in <module>
    main(args)
  File "./Projects/CDP/main.py", line 30, in main
    workspace = cdp(cfg)
  File "/home/s222126776/Projects/CDP/workspaces/cdp.py", line 37, in __init__
    self.sac_smm_cfg = self.cfg['SAC_SMM']
KeyError: 'SAC_SMM'
Traceback (most recent call last):
Traceback (most recent call last):
  File "./Projects/CDP/main.py", line 49, in <module>
  File "./Projects/CDP/main.py", line 49, in <module>
    main(args)
    main(args)
  File "./Projects/CDP/main.py", line 30, in main
  File "./Projects/CDP/main.py", line 30, in main
    workspace = cdp(cfg)
    workspace = cdp(cfg)
  File "/home/s222126776/Projects/CDP/workspaces/cdp.py", line 37, in __init__
  File "/home/s222126776/Projects/CDP/workspaces/cdp.py", line 37, in __init__
    self.sac_smm_cfg = self.cfg['SAC_SMM']
    self.sac_smm_cfg = self.cfg['SAC_SMM']
KeyError: 'SAC_SMM'
KeyError: 'SAC_SMM'
Traceback (most recent call last):
  File "./Projects/CDP/main.py", line 49, in <module>
    main(args)
  File "./Projects/CDP/main.py", line 30, in main
    workspace = cdp(cfg)
  File "/home/s222126776/Projects/CDP/workspaces/cdp.py", line 37, in __init__
    self.sac_smm_cfg = self.cfg['SAC_SMM']
KeyError: 'SAC_SMM'
srun: error: 4gpu-02: task 0: Exited with exit code 1
srun: error: 4gpu-02: task 0: Exited with exit code 1
srun: error: 4gpu-02: task 0: Exited with exit code 1
srun: error: 4gpu-02: task 0: Exited with exit code 1
srun: error: 4gpu-02: task 0: Exited with exit code 1
srun: error: 4gpu-02: task 0: Exited with exit code 1
srun: error: 4gpu-02: task 0: Exited with exit code 1
